spring:
  application:
    name: philkamonitor
telegram:
  bot:
    token: ${BOT_TOKEN}
    chat_id: ${CHAT_ID}
    name: ${BOT_NAME}
forum:
  philka:
    username: ${PHILKA_USERNAME}
    password: ${PHILKA_PASSWORD}
    topic: 47480
proxy:
  address: ${PROXY_ADDRESS}
  port: ${PROXY_PORT}
  username: ${PROXY_USERNAME}
  password: ${PROXY_PASSWORD}
