spring:
  application:
    name: philkamonitor
  datasource:
    url: jdbc:h2:file:./db/philka_posts
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
telegram:
  bot:
    token: ${BOT_TOKEN}
    chat_id: ${CHAT_ID}
    name: ${BOT_NAME}
forum:
  philka:
    username: ${PHILKA_USERNAME}
    password: ${PHILKA_PASSWORD}
    topic: ${TOPIC_NUMBER}
proxy:
  enabled: true
  address: ${PROXY_ADDRESS}
  port: ${PROXY_PORT}
  username: ${PROXY_USERNAME}
  password: ${PROXY_PASSWORD}
hibernate:
  hbm2ddl:
    auto: create-drop

    